routes/web.php
<?php
Route::get('user/login/', 'CustomersController@login');

Route::get('user/register/', 'CustomersController@register');

Route::resource('users', 'UserController')->middleware('Admin');
Route::resource('questions', 'QuestionsController')->middleware('Admin');
Route::resource('quizzes', 'QuizzesController')->middleware('Admin');
Route::resource('exams', 'ExamController')->middleware('customer');
Route::resource('addquestions', 'AddQuestionsController')->middleware('Admin');
Route::resource('results', 'ResultsController')->middleware('customer');
Route::resource('adminresults', 'AdminResultsController')->middleware('Admin');





// Route::group(['middleware' => ['auth']], function () {
//     Route::resource('roles', 'RoleController');
//     Route::resource('users', 'UserController');
//     Route::resource('products', 'ProductController');
// });

Route::get('/user/dashboard', 'CustomersController@dashboard')->name('userposts');
Route::post('/user/dashboard', 'CustomersController@dashboard')->name('userposts');

Route::get('/dashboard', 'DashboardController@index')->name('getposts');


//Route::resource('account', 'ProfileController');
Route::post('/account/update/{id}', 'ProfileController@updateuser')->name('account.updateuser');

//Route::get('account/{id}', ['as' => 'account.edit', 'uses' => 'UserController@edit']);
Route::patch('account/{id}/update', ['as' => 'account.updateuser', 'uses' => 'ProfileController@updateuser']);

Route::get('/', function () {
    return redirect('dashboard');
});
Route::get('/lockscreen', function () {
    return view('accounts.lockscreen');
});
Route::get('/posts', function () {
    return redirect('dashboard');
});
Route::get('/singleboard', function () {
    return view('singleboard');
});
Route::get('/account', 'ProfileController@index');
Route::get('/team', function () {
    return view('team');
});
Route::get('/sendemail', 'SendEmailController@index');
Route::post('/sendinviteemails', 'SendEmailController@send')->name('sendemail.email');
Route::resource('betafeedback', 'MailController');

Route::get('404', ['as' => '404', 'uses' => 'ErrorHandlerController@errorCode404']);
//Route::get('405',['as'=>'405','uses'=>'ErrorHandlerController@errorCode405']);
Auth::routes(['verify' => true]);
// Route::get('/', 'BrandController@create');
Route::get('/verify', 'HomeController@verify');
//Route::get('/brands/index', 'BrandController@index');

app/AddQuestions.php
<?php

namespace App;

use SoftDeletes;
use Overtrue\LaravelFollow\Traits\CanBeLiked;
use Illuminate\Database\Eloquent\Model;

class AddQuestions extends Model
{
    protected $fillable = [
        'id', 'question_id', 'exam_id',
    ];

    protected $table = 'quiz_questions';

    protected $dates = ['deleted_at'];
}

app/Http/Controllers/AddQuestionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Hash;
use App\Question;
use App\Quiz;
use App\AddQuestions;
use Illuminate\Http\Request;
use App\User;

class AddQuestionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $quiz = Quiz::orderBy('created_at', 'desc')->get();
        //$addquestions = AddQuestions::all();
        //$questions = Question::orderBy('created_at', 'desc')->get();

        // $questions = Question::rightJoin('quiz_questions', 'quiz_questions.question_id', '=', 'c.id')
        //     //  ->selectRaw('exam_question.*')

        //     ->get();
        $questions = Question::join('quiz_questions', 'exam_question.id', '=', 'quiz_questions.question_id')
            ->selectRaw('exam_question.*')
            ->get();
        $questionsadd = Question::leftJoin('quiz_questions', 'exam_question.id', '=', 'quiz_questions.question_id')
            ->selectRaw('exam_question.*')
            ->get();
        $data = array(
            'quiz' => $quiz,
            // 'key' => $key,
            'questions' => $questions,
            'questionsadd' => $questionsadd,
        );
        return view('addquestions.index')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('addquestions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'question_id' => 'required',
            'exam_id' => 'required',

        ]);
        $question = array(
            'question_id' => $request->question_id,
            'exam_id' => $request->exam_id,
        );
        AddQuestions::create($question);
        return redirect()->back()
            ->with('success', 'Question added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('addquestions.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        return view('addquestions.edit', compact('question'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question)
    {
        $request->validate([
            'question' => 'required',
            'answers' => 'required',
            'marks' => 'required',
            'negative' => 'required',
            'context' => 'required',
            'level' => 'required',
            'category' => 'required',
            'subject' => 'required',
        ]);

        $question->update($request->all());

        return redirect()->route('questions.index')
            ->with('success', 'Question updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(AddQuestions $addquestion)
    {
        $addquestion->delete();

        return redirect()->back()
            ->with('success', 'Question deleted successfully');
    }
}

resources/views/addquestions/index.blade.php
@extends('layouts.vertical.master')
@section('css')
<!-- third party css -->
<link href="{{ URL::asset('assets/libs/datatables/datatables.min.css')}}" rel="stylesheet" type="text/css" />
<!-- third party css end -->
@endsection
@section('content')
<!-- Start Content-->
<div class="container-fluid">
   <!-- start page title -->

   @if ($message = Session::get('success'))
   <div class="alert alert-success">
      <p>{{ $message }}</p>
   </div>
   @endif
   <div class="row">
        <div class="row">
                <div class="col-12">
                   <div class="page-title-box">
                      <h4 class="page-title">List of Questions</h4> (mapped to quiz)
                   </div>
                </div>
             </div>
      <div class="col-12">
         <div class="card">
            <div class="card-body">
               <table id="basic-datatable" class="table dt-responsive nowrap">
                  <thead>
                     <tr>
                        <th>No</th>
                        <th width="15%">Question</th>
                        <th>Subject</th>
                        <th>category</th>
                        <th>D'Level</th>
                        <th>Action</th>
                     </tr>
                  </thead>
                  <tbody>
                     @foreach ($questions as $question)

                     <tr>
                        <td>{{ $question->id }} </td>
                        <td>{!! $question->question !!}</td>
                        <td>{!! $question->subject !!}</td>
                        <td>{!! $question->category !!}</td>
                        <td>{!! $question->level !!}</td>

                    <td>
                            @if($question->id != $question->question_id)
                            <form action="{{ route('addquestions.destroy',$question->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <select class="form-control">
                                                @foreach($quiz as $quizzes)
                                            {{-- @if($quizzes->id == $keys->exam_id) --}}
                                            @foreach($quiz as $quizzess)
                                            <option value="{{$quizzess->id}}"> {{$quizzess->name}} </option>
                                            @endforeach

                                            {{-- @endif --}}
                                            @endforeach
                                        </select>
                                    </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                    <button type="submit" class="btn btn-danger">Delete To Exam</button>
                                    </div>
                                </form>
                                @endif
                            </td>


                        {{-- <td>
                                @if($question->id == $question->question_id)


                                    @else
                                    <form action="{{ route('addquestions.store') }}" method="POST">
                                        @csrf
                                        <div class="row">
                                            <input class="form-control" id="question_id"  type="hidden" name="question_id" value="{{$question->id}}">
                                            <div class="col-xs-12 col-sm-12 col-md-12">
                                                <div class="form-group">
                                                <select class="form-control" name="exam_id">
                                                    <option> Select Exam </option>
                                                    @foreach($quiz as $quizzes)
                                                    <option value="{{$quizzes->id}}"> {{$quizzes->name}} </option>
                                                    @endforeach
                                                </select>
                                                </div>
                                            </div>
                                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                                <button type="submit" class="btn btn-primary">Add to Exam</button>
                                            </div>
                                        </div>
                                    </form>
                                    @endif

                                    </td> --}}
                                </tr>
                                @endforeach

                            </tbody>
               </table>
            </div>
            <!-- end card body-->
         </div>
         <!-- end card -->
      </div>
      <!-- end col-->
      <div class="row">
            <div class="col-12">
               <div class="page-title-box">
                  <h4 class="page-title">List of All Questions</h4>
               </div>
            </div>
         </div>
      <div class="col-12">
            <div class="card">
               <div class="card-body">
                  <table id="basic-datatable" class="table dt-responsive nowrap">
                     <thead>
                        <tr>
                           <th>No</th>
                           <th width="15%">Question</th>
                           <th>Subject</th>
                           <th>category</th>
                           <th>D'Level</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody>
                        @foreach ($questionsadd as $question)

                        <tr>
                           <td>{{ $question->id }} </td>
                           <td>{!! $question->question !!}</td>
                           <td>{!! $question->subject !!}</td>
                           <td>{!! $question->category !!}</td>
                           <td>{!! $question->level !!}</td>

                       <td>
                               @if($question->id != $question->question_id)
                               <form action="{{ route('addquestions.store') }}" method="POST">
                                    @csrf
                                    <div class="row">
                                        <input class="form-control" id="question_id"  type="hidden" name="question_id" value="{{$question->id}}">
                                        <div class="col-xs-12 col-sm-12 col-md-12">
                                            <div class="form-group">
                                            <select class="form-control" name="exam_id">
                                                <option> Select Exam </option>
                                                @foreach($quiz as $quizzes)
                                                <option value="{{$quizzes->id}}"> {{$quizzes->name}} </option>
                                                @endforeach
                                            </select>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                            <button type="submit" class="btn btn-primary">Add to Exam</button>
                                        </div>
                                    </div>
                                </form>
                                   @endif
                               </td>



                                   </tr>
                                   @endforeach

                               </tbody>
                  </table>
               </div>
               <!-- end card body-->
            </div>
            <!-- end card -->
         </div>
         <!-- end col-->
   </div>
   <!-- end row-->
</div>
<!-- container -->
@endsection
@section('script')
<!-- third party js -->
<script src="{{ URL::asset('assets/libs/datatables/datatables.min.js')}}"></script>
<script src="{{ URL::asset('assets/libs/pdfmake/pdfmake.min.js')}}"></script>
<!-- third party js ends -->
<!-- Datatables init -->
<script src="{{ URL::asset('assets/js/pages/datatables.init.js')}}"></script>
@endsection

resources/views/addquestions/show.blade.php
@extends('layouts.vertical.master')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show user</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('users.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $user->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Details:</strong>
                {{ $user->detail }}
            </div>
        </div>
    </div>
@endsection