routes/web.php
<?php
Route::get('user/login/', 'CustomersController@login');

Route::get('user/register/', 'CustomersController@register');

Route::resource('users', 'UserController')->middleware('Admin');
Route::resource('questions', 'QuestionsController')->middleware('Admin');
Route::resource('quizzes', 'QuizzesController')->middleware('Admin');
Route::resource('exams', 'ExamController')->middleware('customer');
Route::resource('addquestions', 'AddQuestionsController')->middleware('Admin');
Route::resource('results', 'ResultsController')->middleware('customer');
Route::resource('adminresults', 'AdminResultsController')->middleware('Admin');





// Route::group(['middleware' => ['auth']], function () {
//     Route::resource('roles', 'RoleController');
//     Route::resource('users', 'UserController');
//     Route::resource('products', 'ProductController');
// });

Route::get('/user/dashboard', 'CustomersController@dashboard')->name('userposts');
Route::post('/user/dashboard', 'CustomersController@dashboard')->name('userposts');

Route::get('/dashboard', 'DashboardController@index')->name('getposts');


//Route::resource('account', 'ProfileController');
Route::post('/account/update/{id}', 'ProfileController@updateuser')->name('account.updateuser');

//Route::get('account/{id}', ['as' => 'account.edit', 'uses' => 'UserController@edit']);
Route::patch('account/{id}/update', ['as' => 'account.updateuser', 'uses' => 'ProfileController@updateuser']);

Route::get('/', function () {
    return redirect('dashboard');
});
Route::get('/lockscreen', function () {
    return view('accounts.lockscreen');
});
Route::get('/posts', function () {
    return redirect('dashboard');
});
Route::get('/singleboard', function () {
    return view('singleboard');
});
Route::get('/account', 'ProfileController@index');
Route::get('/team', function () {
    return view('team');
});
Route::get('/sendemail', 'SendEmailController@index');
Route::post('/sendinviteemails', 'SendEmailController@send')->name('sendemail.email');
Route::resource('betafeedback', 'MailController');

Route::get('404', ['as' => '404', 'uses' => 'ErrorHandlerController@errorCode404']);
//Route::get('405',['as'=>'405','uses'=>'ErrorHandlerController@errorCode405']);
Auth::routes(['verify' => true]);
// Route::get('/', 'BrandController@create');
Route::get('/verify', 'HomeController@verify');
//Route::get('/brands/index', 'BrandController@index');

app/Question.php
<?php

namespace App;

use SoftDeletes;
use Overtrue\LaravelFollow\Traits\CanBeLiked;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{

    protected $fillable = [
        'id', 'question', 'option_1', 'option_2', 'option_3', 'option_4', 'option_5', 'option_6', 'category', 'level', 'subject', 'created_by', 'answers', 'marks', 'negative', 'context',
    ];

    protected $table = 'exam_question';


    protected $dates = ['deleted_at'];
}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Hash;
use App\Question;
use Illuminate\Http\Request;
use App\User;

class QuestionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index(Request $request)
    {

        $questions = Question::orderBy('created_at', 'desc')->get();
        return view('questions.index', compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('questions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'question' => 'required',

            'answers' => 'required',
            'marks' => 'required',
            'negative' => 'required',
            'context' => 'required',
            'level' => 'required',
            'category' => 'required',
            'subject' => 'required',

        ]);
        $question = array(
            'question' => $request->question,
            'option_1' => $request->option_1,
            'option_2' => $request->option_2,
            'option_3' => $request->option_3,
            'option_4' => $request->option_4,
            'option_5' => $request->option_5,
            'option_6' => $request->option_6,
            'answers' => $request->answers,
            'marks' => $request->marks,
            'negative' => $request->negative,
            'subject' => $request->subject,
            'level' => $request->level,
            'category' => $request->category,
            'context' => $request->context,
        );
        Question::create($question);
        return redirect()->route('questions.index')
            ->with('success', 'Question created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('questions.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        return view('questions.edit', compact('question'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Question $question)
    {
        $request->validate([
            'question' => 'required',
            'answers' => 'required',
            'marks' => 'required',
            'negative' => 'required',
            'context' => 'required',
            'level' => 'required',
            'category' => 'required',
            'subject' => 'required',
        ]);

        $question->update($request->all());

        return redirect()->route('questions.index')
            ->with('success', 'Question updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        $question->delete();

        return redirect()->route('questions.index')
            ->with('success', 'Question deleted successfully');
    }
}

resources/views/questions/index.blade.php
@extends('layouts.vertical.master')
@section('css')
        <!-- third party css -->
        <link href="{{ URL::asset('assets/libs/datatables/datatables.min.css')}}" rel="stylesheet" type="text/css" />
        <!-- third party css end -->
@endsection

@section('content')

                    <!-- Start Content-->
                    <div class="container-fluid">

                        <!-- start page title -->
                        <div class="row">
                                <div class="col-12">
                                   <div class="page-title-box">
                                      <div class="page-title-right">
                                            <a class="btn btn-success" href="{{ route('questions.create') }}"> Create Question</a>

                                      </div>
                                      <h4 class="page-title">Questions Managment</h4>

                            </div>
                                </div>
                             </div>

                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">
                                @if ($message = Session::get('success'))
                                        <div class="alert alert-success">
                                            <p>{{ $message }}</p>
                                        </div>
                                    @endif

                                        <table id="basic-datatable" class="table dt-responsive nowrap">
                                                <thead><tr>
                                                        <th>No</th>
                                                        <th width="20px">Question</th>
                                                        <th>+ve Marks</th>
                                                        <th>-ve Marks</th>
                                                        <th>Subject</th>
                                                        <th>category</th>
                                                        <th>D'Level</th>
                                                        <th>Action</th>
                                                    </tr>  </thead>

                                                    <tbody>
                                                            @foreach ($questions as $question)
                                                            <tr>
                                                        <td>{{ $question->id }}</td>
                                                        <td>{!! $question->question !!}</td>
                                                        <td>{!! $question->marks !!}</td>
                                                        <td>{!! $question->negative !!}</td>
                                                        <td>{!! $question->subject !!}</td>
                                                        <td>{!! $question->category !!}</td>
                                                        <td>{!! $question->level !!}</td>
                                                        <td>
                                                            <form action="{{ route('questions.destroy',$question->id) }}" method="POST">

                                                                {{-- <a class="btn btn-info" href="{{ route('questions.show',$question->id) }}">Show</a> --}}

                                                                <a class="btn btn-primary" href="{{ route('questions.edit',$question->id) }}">Edit</a>

                                                                @csrf
                                                                @method('DELETE')

                                                                <button type="submit" class="btn btn-danger">Delete</button>
                                                            </form>
                                                        </td>
                                                    </tr> @endforeach</tbody>




                                        </table>

                                    </div> <!-- end card body-->
                                </div> <!-- end card -->
                            </div><!-- end col-->
                        </div>
                        <!-- end row-->




                    </div> <!-- container -->
@endsection

@section('script')

        <!-- third party js -->
        <script src="{{ URL::asset('assets/libs/datatables/datatables.min.js')}}"></script>
        <script src="{{ URL::asset('assets/libs/pdfmake/pdfmake.min.js')}}"></script>
        <!-- third party js ends -->

        <!-- Datatables init -->
        <script src="{{ URL::asset('assets/js/pages/datatables.init.js')}}"></script>

@endsection

resources/views/questions/show.blade.php
@extends('layouts.vertical.master')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show user</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('users.index') }}"> Back</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $user->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Details:</strong>
                {{ $user->detail }}
            </div>
        </div>
    </div>
@endsection